monitor.alsa.rules = [
     {
       matches = [
         {
           object.id = "any"
         }
       ]
       actions = {
         update-props = {
           -- Forces streams to rescue to the next available target
           rescue-streams = true
         }
       }
      }
]
